### PR TITLE
Update figure files

### PR DESCRIPTION
**Pull request by murphymadeleine21**
Figure 5:
- we keep the simulated tensor as is, but scale the noise to have the same standard deviation
- add titles to 5b and 5c. I have "Factorization with 50% of Values Removed" and "Factorization with Noise Added". Any thoughts on better titles appreciated. 
- We now have 3 iterations for the missingness corrindex plot. For each level of missingness, at each iteration, I create a new simulated tensor (different each time) and remove 50% of its values (different each time, no seed set) and then run the factorization and get the corrindex. Later, if we wanted to see how the factorization differs on each iteration without changing the values removed or the simulated tensor generated, I could set the seeds for both.
- For the noise, I don't generate a new tensor each time but rather stick with the same original tensor created. On each iteration, I create a noise element of the right size and std, and then add it to the simulated tensor in multiplicates (i.e. multiply it by 10, 100, etc before adding). If we wanted, we could change this to be more like the missingness calculation - i.e. create a new tensor for each iteration and/or create a new noise element for each scalar value of noise. For now, its really just creating 3 noisy tensor elements and multiplying that before addition to see how the factorization changes.

fig 2:
- change sizing/aesthetic changes of yticks

I'll post what Fig5 looks like once it builds.

### CODE REVIEW

**Review by aarmey — APPROVED** [review]

**Comment by murphymadeleine21** [comment]
The figures are looking good, however I want to try a few more changes.
First, I changed one of the curve parameter values in component 1 to see if things look a bit better. I made its initial start value slightly lower to see if it will distinguish more nicely from component 3. It usually looks like this:
Screen Shot 2022-05-04 at 10 14 52 PM
But I think if the blue curve starts at 0.05 it may look more interesting (and perhaps the factorization will separate these curves better? I'm not sure). We'll see, it might be arbitrary in terms of how the factorization performs. 

Second, I'd like the noise corrindex plot to run 10 times and get the average. 3 doesn't feel like enough given how much variation we see in plot c. I'd like to know that when adding 1 "unit" of noise we get consistently low corrindexes (if we can say 10 denotes "consistent"...). 

Other cosmetic changes are minor.

**Review by aarmey — CHANGES_REQUESTED** [review]
Looks like there's a size mismatch build error.

**Comment by murphymadeleine21** [comment]
Just now, I pushed a change that would make us do our noise repetitions differently (and I think possibly better?).
Instead of having 1 tensor that we generate 10 different noise tensors to be scaled and added to, we create a new tensor each time, create noise with the same std as that tensor, and then scale and add the noise. Thus were comparing 5 unique tensors when different levels (1 times std, 10 times std, etc) of noise are added, rather than just generating a bunch of slightly different looking noise that all end up having the same std of the one original tensor generated for this figure. I'm hoping this will give a better overview of how the method is performing.

**Comment by murphymadeleine21** [comment]
Other changes to this branch included some aesthetic changes, and setting the seed back to nothing (or just random?) by calling `np.random.seed()` just once before the repetitive normal calculations, rather than at every iteration.

**Pull request merged**
