### PR TITLE
run regular CP on 4D

### PR DESCRIPTION
**Pull request by murphymadeleine21**
This code worked for 5 components (ran for both continuous and regular CP methods up to then), and then I got an error within parafac?
Looks like it occurs during the SVD initialization in the function _asarray_validated. I get an error saying it cannot contain Nans or Infs. I'm not sure why it just had this error on component number 6? All other initializations worked and there shouldn't be an issue with the Nans? But I may be missing something as I don't have a super strong understanding of parafac.

### CODE REVIEW

**Comment by aarmey** [comment]
You have missing values. Use `perform_CP` within tensorpack.

**Comment by murphymadeleine21** [comment]
@aarmey Can you possibly check the dependency error that is going on here? I think my fix should have worked but this won't build.

**Comment by aarmey** [comment]
I'm not sure why this happens, but it seems to go away if you just restart the build.

**Comment by murphymadeleine21** [comment]
figure1

**Comment by murphymadeleine21** [comment]
Not sure why I can't see the figure files in the actions.

**Comment by murphymadeleine21** [comment]
Silly issue, the deg freedom is now less than 256 for first factorization.

**Comment by murphymadeleine21** [comment]
Somehow my change in pyproject.toml on another branch may have transferred over. I want to import that library for the imputations but it's causing issues with poetry for me (I posted in slack about that a few days ago)

**Comment by aarmey** [comment]
Don't import systemsSerology as a package like this—I don't think we have it setup properly to do so. If you need functions or even entire files from it just copy them over.

**Pull request merged**
