### PR TITLE
Add unimodal assertion

### PR DESCRIPTION
**Pull request by murphymadeleine21**
This is a very simple way to check that the continuous factor modes are unimodal. A few things to note.
Our definition of unimodal here is that the colors are changing in one direction - so our factor is monotonically increasing or decreasing essentially. Some would define unimodal as increasing, then constant, then decreasing (a distribution with one clear peak, like the normal). But here, I just have a simple check that looks for increasing/decreasing behavior as time increases.

The problem is, this assertion is definitely going to fail quite a bit, and simply break the code. Not sure what to do in the case of our assertion failing.

Another thing to note--if we only check to see if we have the unimodal behavior starting at time 1, instead of time 0, I believe we will pass the assertion statement much more often (or maybe all of the time). I just did a little try out of code for that on one factorization. All of the 5 factors were unimodal if we check t=1+. Only 2 of the factors were unimodal when checking the entire array. As I said in slack, I think this may indicate something about the structure of the data rather than the factorization method itself?

### CODE REVIEW

**Comment by aarmey** [comment]
First, completely right about unimodal. I think unidirectional might be the proper term.

**Review by aarmey — COMMENTED** [review]
I rearranged it into a more general test.

I agree—every time this has failed, the issue has been the very first entry.

**Comment by aarmey** [comment]
Is the output from `curve()` always unidirectional? All the values stem from there...

**Comment by aarmey** [comment]
Yep—the output from `curve()` isn't unidirectional, but the time vector is. Something is wrong in that function.

**Comment by murphymadeleine21** [comment]
Hm. Well, it's the exact same equation from Zohar.

**Comment by murphymadeleine21** [comment]
Oh! Found a small bug. Will fix.

**Comment by murphymadeleine21** [comment]
What method did you use to quickly check if the curve outputs are unidirectional? Just adding a line where we call our assertion function on the curve output?

**Comment by aarmey** [comment]
I just printed them out.

**Comment by aarmey** [comment]
@murphymadeleine21 you found the problem here. I've now additionally added bounds to avoid nan's in the output. If this builds I'll merge.

**Pull request merged**
