### PR TITLE
change curve to zohar curve

### PR DESCRIPTION
**Pull request by murphymadeleine21**
This is pretty straightforward, but maybe we can do some of the other requested changes to the tensor file on this branch.

Also, I installed poetry and then had my visual studio code notebooks/scripts running in the python virtual environment. For this to work, I also had to run "poetry add ipykernel". I think this made some changes to the poetry files? When I went to add stuff to commit, it had changes for poetry.lock and pyproject.toml. I'm not sure what to do about this -- should I include these changes? I feel like whatever changes were made to those files are essential to me being able to run the code?

### CODE REVIEW

**Review by cyrillustan — APPROVED** [review]
Yes, you should add `iPyKernel` to poetry.

**Comment by murphymadeleine21** [comment]
Cyrillus and I just went through the code and set tFac.cFactor as the P matrix and tFac.time as v.

**Review by aarmey — CHANGES_REQUESTED** [review]
Great. Check that this builds.

**Comment by murphymadeleine21** [comment]
This is working now so I'll merge it.

**Pull request merged**
