### PR TITLE
Change initialization, also git ignore file

### PR DESCRIPTION
**Pull request by murphymadeleine21**
Here is the 3D decomposition we talked about for better initialization. We can see how this runs on this branch. I'm just using regular parafac not CMTF necessarily.

### CODE REVIEW

**Review by cyrillustan — APPROVED** [review]
Looks about right! See why it doesn't build and fix that before merging. One unimportant question, why not use the CP in tensorpack?

**Comment by murphymadeleine21** [comment]
@cyrillustan  The only reason I used tensorly parafac is because that's what we do in Fig 6 in systemsSerology. But we could use CP from tensorpack I suppose? I just based if off what we have done before

**Comment by cyrillustan** [comment]
Oh I see, sure we don't have to use parafac then (unless there is missing value)

**Comment by murphymadeleine21** [comment]
Why did you guys use parafac in the first place for the systems serology paper? That change was made after I left for the summer I believe.

**Comment by cyrillustan** [comment]
We didn't have tensorpack at the time, and it is equivalent to our version if there is no missing values

**Pull request merged**
